const C={green:'#176b55',red:'#d75446',blue:'#3277b8',orange:'#e49242',ink:'#15231f',grid:'#e6ebe7'};
const profileColors=['#d75446','#176b55','#3277b8','#e49242','#7d5ba6'];
const plotConfig={responsive:true,displaylogo:false,modeBarButtonsToRemove:['lasso2d','select2d']};
const baseLayout={margin:{l:62,r:24,t:30,b:48},paper_bgcolor:'rgba(0,0,0,0)',plot_bgcolor:'rgba(0,0,0,0)',font:{family:'Inter, sans-serif',color:C.ink,size:11},xaxis:{gridcolor:C.grid,automargin:true},yaxis:{gridcolor:C.grid,automargin:true},legend:{orientation:'h',y:1.12}};
let D,times,series,labels,map,rainLayer,plumeLayer,pollutantPlumeLayer,shipLayer,playing=false,playTimer=null;
const responseKeys=['CPC','SMPSTotal','GeometricMeanDiameter','GeometricStdDev','ModeDiameter','FractionBelow30nm','FractionBelow100nm','FractionAbove100nm'];
const defaultPlot=['CPC','SMPSTotal','Temperature','WindSpeed','ARPA_NO2','AQ_NO2'];
const siteId=new URLSearchParams(location.search).get('site')||'rome';
const siteSelect=document.querySelector('#siteSelect');siteSelect.value=siteId;siteSelect.onchange=e=>{const loading=document.querySelector('#loading');if(loading)loading.textContent='Standort wird geladen …';const url=new URL(location.href);url.searchParams.set('site',e.target.value);url.searchParams.delete('v');location.assign(url.href)};

fetch(`data/${siteId}-monitoring.json`).then(r=>{if(!r.ok)throw Error(`${siteId}-monitoring.json fehlt`);return r.json()}).then(init).catch(e=>{document.querySelector('#loading').textContent='Dashboard-Daten konnten nicht geladen werden: '+e.message});

function init(data){D=data;times=data.time.map(x=>new Date(x));series=data.series;labels=data.labels||{};const years=[...new Set(times.map(t=>t.getFullYear()))].join('/'),smps=hasSMPS(),s=data.site;
  document.querySelector('#siteEyebrow').textContent=data.site.name.toUpperCase()+' · '+years;
  const airParts=[];if(finite(+s.airLatitude)&&finite(+s.airLongitude)&&s.airName)airParts.push(`${s.airName}, ${distanceKm(s.latitude,s.longitude,s.airLatitude,s.airLongitude).toFixed(2)} km`);if(finite(+s.air2Latitude)&&finite(+s.air2Longitude)&&s.air2Name)airParts.push(`${s.air2Name}, ${distanceKm(s.latitude,s.longitude,s.air2Latitude,s.air2Longitude).toFixed(2)} km`);document.querySelector('#methodSpatial').textContent=`Wetter: ${s.weatherName}, ${distanceKm(s.latitude,s.longitude,s.weatherLatitude,s.weatherLongitude).toFixed(2)} km. Luftqualität: ${airParts.join(' und ')||'keine Stationsdaten'}. Lokale Strömung und Emissionen können am Messpunkt abweichen.`;
  document.querySelector('#period').textContent=`${fmt(times[0],true)} – ${fmt(times.at(-1),true)}`;
  document.querySelector('#generated').textContent=`· Export ${data.generated}`;
  document.querySelector('#profileTabButton').classList.toggle('hidden',!smps);document.querySelector('#dataHeatmapControl').classList.toggle('hidden',!smps);document.querySelector('#mapHeatmapControl').classList.toggle('hidden',!smps);document.querySelector('#shipMapLegend').classList.toggle('hidden',!series.ShipPassages);document.querySelector('#shipMethodCard').classList.toggle('hidden',!series.ShipPassages);document.querySelector('#footerData').textContent=siteId==='hoheduene'?'Daten: TSI 3789/3783/3750 · Partector · Schiffspassagen · Open-Meteo · LUNG M-V/UBA':'Daten: CPC · SMPS · Meteostat/Open-Meteo · ARPA Lazio/Hamburger Luftmessnetz';document.querySelector('#corrSubtitle').textContent=smps?'SMPS-Kanäle sind bewusst ausgeschlossen; verglichen werden Gesamtzahl und Kennwerte der Verteilung.':'Jeder Partikelzähler kann als Zielgröße mit Wetter, Luftqualität und der Anzahl der Schiffspassagen verglichen werden.';
  buildSelectors();bindTabs();drawOverview();drawData();drawCorrelations();if(smps)drawProfiles();initMap();updateMap();
  document.querySelector('#loading').remove();
}
function hasSMPS(){return D?.site?.hasSMPS!==false&&D?.heatmap?.time?.length>0}
function particleKeys(){return D?.site?.primaryKeys?.filter(k=>series[k])||['CPC','SMPSTotal'].filter(k=>series[k])}
function referenceKey(){return D?.site?.referenceKey||particleKeys()[0]||'CPC'}
function label(k){return labels[k]||k.replace(/^ARPA_/,'ARPA ').replace(/^AQ17SM_/,'17SM ').replace(/^AQ_/,'13ST ')}
function fmt(d,dateOnly=false){return new Intl.DateTimeFormat('de-DE',dateOnly?{day:'2-digit',month:'2-digit',year:'numeric'}:{day:'2-digit',month:'2-digit',hour:'2-digit',minute:'2-digit'}).format(d)}
function distanceKm(a,b,c,d){const R=6371,p=x=>x*Math.PI/180,da=p(c-a),db=p(d-b),q=Math.sin(da/2)**2+Math.cos(p(a))*Math.cos(p(c))*Math.sin(db/2)**2;return 2*R*Math.atan2(Math.sqrt(q),Math.sqrt(1-q))}
function vals(k){return (series[k]||[]).map(v=>v==null?NaN:+v)}
function finite(v){return Number.isFinite(v)}
function mean(a){const f=a.filter(finite);return f.length?f.reduce((s,v)=>s+v,0)/f.length:NaN}
function sum(a){const f=a.filter(finite);return f.length?f.reduce((s,v)=>s+v,0):NaN}
function median(a){const f=a.filter(finite).sort((a,b)=>a-b);if(!f.length)return NaN;const n=f.length;return n%2?f[(n-1)/2]:(f[n/2-1]+f[n/2])/2}
function sd(a){const m=mean(a),f=a.filter(finite);return f.length>1?Math.sqrt(f.reduce((s,v)=>s+(v-m)**2,0)/(f.length-1)):NaN}
function zscore(a){const m=mean(a),s=sd(a);return a.map(v=>finite(v)&&s?((v-m)/s):NaN)}
function paired(a,b){const x=[],y=[];for(let i=0;i<Math.min(a.length,b.length);i++)if(finite(a[i])&&finite(b[i])){x.push(a[i]);y.push(b[i])}return{x,y}}
function pearson(a,b){const p=paired(a,b),mx=mean(p.x),my=mean(p.y);let n=0,dx=0,dy=0;for(let i=0;i<p.x.length;i++){const x=p.x[i]-mx,y=p.y[i]-my;n+=x*y;dx+=x*x;dy+=y*y}return{r:dx&&dy?n/Math.sqrt(dx*dy):NaN,n:p.x.length,x:p.x,y:p.y}}
function ranks(a){const order=a.map((v,i)=>[v,i]).sort((x,y)=>x[0]-y[0]),r=Array(a.length);for(let i=0;i<order.length;){let j=i;while(j+1<order.length&&order[j+1][0]===order[i][0])j++;const q=(i+j+2)/2;for(let k=i;k<=j;k++)r[order[k][1]]=q;i=j+1}return r}
function corr(a,b,method){const p=paired(a,b);return method==='Spearman'?{...pearson(ranks(p.x),ranks(p.y)),x:p.x,y:p.y}:pearson(p.x,p.y)}
function resample(k,minutes){const y=vals(k),step=Math.max(1,minutes/5),x=[],o=[],aggregate=k==='ShipPassages'?sum:mean;for(let i=0;i<y.length;i+=step){x.push(times[i]);o.push(aggregate(y.slice(i,i+step)))}return{x,y:o}}
function shift(a,n){if(!n)return a.slice();return n>0?Array(n).fill(NaN).concat(a.slice(0,-n)):a.slice(-n).concat(Array(-n).fill(NaN))}
function plot(id,traces,layout={}){Plotly.react(id,traces,{...baseLayout,...layout,xaxis:{...baseLayout.xaxis,...(layout.xaxis||{})},yaxis:{...baseLayout.yaxis,...(layout.yaxis||{})}},plotConfig)}

function bindTabs(){document.querySelectorAll('.tabs button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.tabs button,.tab').forEach(x=>x.classList.remove('active'));b.classList.add('active');document.querySelector('#'+b.dataset.tab).classList.add('active');setTimeout(()=>{document.querySelectorAll('.tab.active .js-plotly-plot').forEach(g=>Plotly.Plots.resize(g));if(b.dataset.tab==='map')map.invalidateSize()},0)})}
function buildSelectors(){
  const available=Object.keys(series),particles=hasSMPS()?responseKeys.filter(k=>available.includes(k)):particleKeys(),scalar=available.filter(k=>!['WindDirection'].includes(k)),defaults=hasSMPS()?defaultPlot:[...particleKeys(),'ShipPassages','WindSpeed'];
  document.querySelector('#dataVariables').innerHTML=scalar.map(k=>`<label><input type="checkbox" value="${k}" ${defaults.includes(k)?'checked':''}> ${label(k)}</label>`).join('');
  document.querySelector('#corrResponse').innerHTML=particles.map(k=>`<option value="${k}">${label(k)}</option>`).join('');
  const predictors=available.filter(k=>!particles.includes(k)&&k!=='WindDirection'&&k!=='ShipSpeed');
  document.querySelector('#corrPredictors').innerHTML=predictors.map(k=>`<label><input type="checkbox" value="${k}" ${['Temperature','WindSpeed','ShipPassages','ARPA_NO2','AQ_NO2'].includes(k)?'checked':''}><span>${label(k)}</span></label>`).join('');
  const airKeys=available.filter(k=>k.startsWith('ARPA_')||k.startsWith('AQ_')||k.startsWith('AQ17SM_'));document.querySelector('#mapPollutants').innerHTML=airKeys.map(k=>`<label><input type="checkbox" value="${k}" ${['ARPA_NO2','ARPA_PM10','AQ_NO2','AQ_PM10'].includes(k)?'checked':''}> ${label(k).replace(/ \(.*\)$/,'')}</label>`).join('');document.querySelectorAll('#mapPollutants input').forEach(x=>x.onchange=updateMap);document.querySelector('#hidePollutants').onclick=()=>{document.querySelectorAll('#mapPollutants input').forEach(x=>x.checked=false);updateMap()};
  document.querySelector('#mapCloudPollutants').innerHTML=airKeys.map(k=>`<label><input type="checkbox" value="${k}" ${['ARPA_NO2','AQ_NO2'].includes(k)?'checked':''}><i style="background:${pollutantColor(k)}"></i> ${label(k)}</label>`).join('');document.querySelectorAll('#mapCloudPollutants input').forEach(x=>x.onchange=updateMap);document.querySelector('#hideCloudPollutants').onclick=()=>{document.querySelectorAll('#mapCloudPollutants input').forEach(x=>x.checked=false);updateMap()};
  ['dataAverage','dataMode','showHeatmap'].forEach(id=>document.querySelector('#'+id).onchange=drawData);document.querySelectorAll('#dataVariables input').forEach(x=>x.onchange=drawData);
  ['corrResponse','corrMethod','corrAverage'].forEach(id=>document.querySelector('#'+id).onchange=drawCorrelations);document.querySelectorAll('#corrPredictors input').forEach(x=>x.onchange=drawCorrelations);document.querySelector('#corrLag').oninput=e=>{document.querySelector('#lagValue').value=e.target.value+' h';drawCorrelations()};
}

function drawOverview(){if(!hasSMPS())return drawInstrumentOverview();const c=resample('CPC',60),s=resample('SMPSTotal',60),p=paired(c.y,s.y),r=corr(c.y,s.y,'Spearman');
  document.querySelector('#quickCorr').textContent=finite(r.r)?r.r.toFixed(3):'–';document.querySelector('#quickCorrText').textContent=`CPC–SMPS Spearman · n=${r.n}`;
  document.querySelector('#overviewStats').innerHTML=`<span><b>${mean(p.x).toFixed(0)}</b>CPC #/cm³</span><span><b>${mean(p.y).toFixed(0)}</b>SMPS #/cm³</span><span><b>${times.length}</b>5-min-Zeitpunkte</span>`;
  plot('overviewPlot',[{x:c.x,y:c.y,name:'CPC',line:{color:C.red}},{x:s.x,y:s.y,name:'SMPS',line:{color:C.blue}}],{hovermode:'x unified',yaxis:{title:'#/cm³'}});
  const pr=pearson(c.y,s.y),sr=corr(c.y,s.y,'Spearman'),fit=linearFit(p.x,p.y),traces=[{x:p.x,y:p.y,mode:'markers',name:'Stundenmittel',marker:{size:7,color:C.green,opacity:.42},hovertemplate:'CPC %{x:.0f}<br>SMPS %{y:.0f}<extra></extra>'}];
  if(fit){const xx=[Math.min(...p.x),Math.max(...p.x)];traces.push({x:xx,y:xx.map(x=>fit.a*x+fit.b),mode:'lines',name:'Lineare Anpassung',line:{color:C.red,width:2,dash:'dash'},hoverinfo:'skip'})}
  plot('overviewCorrelationPlot',traces,{xaxis:{title:'CPC-Gesamtanzahl (#/cm³)'},yaxis:{title:'SMPS-Gesamtanzahl (#/cm³)'},legend:{orientation:'h',y:1.1}});
  document.querySelector('#overviewCorrStats').textContent=`Gemeinsame Stundenmittel: n=${p.x.length} · Pearson r=${finite(pr.r)?pr.r.toFixed(3):'–'} · Spearman r=${finite(sr.r)?sr.r.toFixed(3):'–'}`
}
function drawInstrumentOverview(){const keys=particleKeys(),colors=[C.red,C.blue,C.green,C.orange],hourly=Object.fromEntries(keys.map(k=>[k,resample(k,60)])),ref=keys[0],comparisons=keys.slice(1);document.querySelector('#overviewTitle').textContent='Vier Partikelzähler und Schiffspassagen im Vergleich';document.querySelector('#overviewSubtitle').textContent='Wasser- und Butanol-CPC sowie Partector gemeinsam mit Wetter, Luftqualität und Schiffsverkehr.';document.querySelector('#overviewStats').innerHTML=keys.map(k=>`<span><b>${mean(vals(k)).toFixed(0)}</b>${label(k).replace(/ \(.*\)$/,'')}</span>`).join('');
  const first=comparisons[0],quick=corr(hourly[ref].y,hourly[first].y,'Spearman');document.querySelector('#quickCorr').textContent=finite(quick.r)?quick.r.toFixed(3):'–';document.querySelector('#quickCorrText').textContent=`${label(ref).replace(/ \(.*\)$/,'')}–${label(first).replace(/ \(.*\)$/,'')} Spearman · n=${quick.n}`;
  const timeTraces=keys.map((k,i)=>({x:hourly[k].x,y:hourly[k].y,name:label(k).replace(/ \(.*\)$/,''),line:{color:colors[i]}}));if(series.ShipPassages){const ships=resample('ShipPassages',60);timeTraces.push({x:ships.x,y:ships.y,name:'Schiffspassagen',type:'bar',yaxis:'y2',marker:{color:'rgba(228,146,66,.26)'}})}plot('overviewPlot',timeTraces,{hovermode:'x unified',yaxis:{title:'Partikel #/cm³'},yaxis2:{title:'Schiffe/h',overlaying:'y',side:'right',showgrid:false}});
  document.querySelector('#overviewCorrelationTitle').textContent=`Instrumentvergleich gegen ${label(ref).replace(/ \(.*\)$/,'')}`;const traces=[],summaries=[];comparisons.forEach((k,i)=>{const p=paired(hourly[ref].y,hourly[k].y),pr=pearson(p.x,p.y),sr=corr(p.x,p.y,'Spearman'),fit=linearFit(p.x,p.y),color=colors[i+1];traces.push({x:p.x,y:p.y,mode:'markers',name:label(k).replace(/ \(.*\)$/,''),marker:{size:6,color,opacity:.38}});if(fit&&p.x.length){const xx=[Math.min(...p.x),Math.max(...p.x)];traces.push({x:xx,y:xx.map(x=>fit.a*x+fit.b),mode:'lines',showlegend:false,line:{color,width:1.7,dash:'dash'},hoverinfo:'skip'})}summaries.push(`${label(k).replace(/ \(.*\)$/,'')}: Pearson ${finite(pr.r)?pr.r.toFixed(3):'–'}, Spearman ${finite(sr.r)?sr.r.toFixed(3):'–'} (n=${p.x.length})`)});plot('overviewCorrelationPlot',traces,{xaxis:{title:label(ref)},yaxis:{title:'Vergleichsgerät (#/cm³)'},legend:{orientation:'h',y:1.12}});document.querySelector('#overviewCorrStats').textContent=summaries.join(' · ')}
function linearFit(x,y){if(x.length<2)return null;const mx=mean(x),my=mean(y),den=x.reduce((s,v)=>s+(v-mx)**2,0);if(!den)return null;const a=x.reduce((s,v,i)=>s+(v-mx)*(y[i]-my),0)/den;return{a,b:my-a*mx}}
function monday(d){const x=new Date(d),day=(x.getDay()+6)%7;x.setHours(0,0,0,0);x.setDate(x.getDate()-day);return x.getTime()}
function groupBy(T,key){const g=new Map;T.x.forEach((d,i)=>{const k=key(d);if(!g.has(k))g.set(k,[]);g.get(k).push(T.y[i])});return{x:[...g.keys()].map(x=>new Date(+x)),y:[...g.values()].map(mean)}}
function dayType(T){const a=[[],[]];T.x.forEach((d,i)=>a[d.getDay()===0||d.getDay()===6?1:0].push(T.y[i]));return a.map(mean)}

function drawData(){const keys=[...document.querySelectorAll('#dataVariables input:checked')].map(x=>x.value),avg=+document.querySelector('#dataAverage').value,mode=document.querySelector('#dataMode').value,show=hasSMPS()&&document.querySelector('#showHeatmap').checked;const traces=[];const colors=[C.red,C.blue,C.green,C.orange,'#7d5ba6','#4f9298','#a26245'];const upper=show?[.47,1]:[0,1],layout={hovermode:'x unified',xaxis:{anchor:'y'},yaxis:{title:mode==='standard'?'Standardisierte Abweichung':(keys[0]?label(keys[0]):''),domain:upper}};
  keys.forEach((k,i)=>{const T=resample(k,avg),y=mode==='standard'?zscore(T.y):T.y,tr={x:T.x,y,name:label(k),line:{color:colors[i%colors.length]}};if(mode==='axes'&&i){const ax='y'+(i+1);tr.yaxis=ax;layout[ax.replace('y','yaxis')]={title:{text:label(k),font:{color:colors[i%colors.length]}},tickfont:{color:colors[i%colors.length]},overlaying:'y',side:i%2?'right':'left',anchor:'free',autoshift:true,showgrid:false}}traces.push(tr)});
  if(show){const H=D.heatmap;traces.push({x:H.time,y:H.sizes,z:H.z.map(row=>row.map(v=>v>0?Math.log10(v):null)),type:'heatmap',xaxis:'x2',yaxis:'y99',colorscale:'Turbo',name:'SMPS-Verteilung',colorbar:{title:'log₁₀',len:.34,y:.17}});layout.xaxis2={domain:[0,.94],anchor:'y99',title:'Datum'};layout.yaxis99={domain:[0,.34],type:'log',title:'SMPS nm'};layout.legend={orientation:'h',y:1.08,font:{size:10}}}
  document.querySelector('#dataPlot').style.height=show?'650px':'430px';plot('dataPlot',traces,layout)
}

function drawCorrelations(){const response=document.querySelector('#corrResponse').value,predictors=[...document.querySelectorAll('#corrPredictors input:checked')].map(x=>x.value),method=document.querySelector('#corrMethod').value,avg=+document.querySelector('#corrAverage').value,lag=+document.querySelector('#corrLag').value;if(!response||!predictors.length){['corrBars','corrScatter','corrTime'].forEach(id=>Plotly.purge(id));document.querySelector('#corrTable').innerHTML='<tr><td colspan="4">Bitte mindestens einen Umweltparameter auswählen.</td></tr>';return}const Y=resample(response,avg),lagBins=Math.round(lag*60/avg),rows=predictors.map(k=>{const X=resample(k,avg),xy=corr(Y.y,shift(X.y,lagBins),method);return{k,X,xy}});
  plot('corrBars',[{x:rows.map(x=>x.xy.r),y:rows.map(x=>label(x.k)),type:'bar',orientation:'h',marker:{color:rows.map(x=>x.xy.r>=0?C.green:C.red)}}],{margin:{l:170,r:30,t:20,b:45},xaxis:{range:[-1,1],title:method+' r'}});
  document.querySelector('#corrTable').innerHTML=rows.map(x=>`<tr><td>${label(x.k)}</td><td><b>${finite(x.xy.r)?x.xy.r.toFixed(3):'–'}</b></td><td>${x.xy.n}</td><td>${strength(x.xy.r)}</td></tr>`).join('');const first=rows[0];
  plot('corrScatter',[{x:first.xy.x,y:first.xy.y,mode:'markers',marker:{size:7,color:C.green,opacity:.45}}],{title:{text:`${label(first.k)} · r=${first.xy.r.toFixed(3)}`,font:{size:13}},xaxis:{title:label(first.k)},yaxis:{title:label(response)},showlegend:false});
  const xShift=shift(first.X.y,lagBins);plot('corrTime',[{x:Y.x,y:zscore(Y.y),name:label(response),line:{color:C.red}},{x:Y.x,y:zscore(xShift),name:label(first.k),line:{color:C.green}}],{title:{text:'Standardisierte Zeitverläufe',font:{size:13}},hovermode:'x unified',yaxis:{title:'z-Wert'}})
}
function strength(r){const a=Math.abs(r);if(!finite(a))return'keine Auswertung';if(a>=.7)return'stark';if(a>=.4)return'mittel';if(a>=.2)return'schwach';return'sehr schwach'}

function localDateValue(d){const p=n=>String(n).padStart(2,'0');return`${d.getFullYear()}-${p(d.getMonth()+1)}-${p(d.getDate())}`}
function pickerMarkup(items){return items.map((name,i)=>`<label><input type="checkbox" value="${i}" ${i===0?'checked':''}><span>${name}</span></label>`).join('')}
function bindProfilePicker(id){const box=document.querySelector('#'+id);box.querySelectorAll('input').forEach(x=>x.onchange=()=>{const checked=[...box.querySelectorAll('input:checked')];if(checked.length>5)x.checked=false;const now=[...box.querySelectorAll('input:checked')];box.querySelectorAll('input').forEach(q=>q.disabled=!q.checked&&now.length>=5);drawProfiles()})}
function setupProfileControls(){const H=D.heatmap,ht=H.time.map(x=>new Date(x)),from=document.querySelector('#profileFrom'),to=document.querySelector('#profileTo');from.min=to.min=localDateValue(ht[0]);from.max=to.max=localDateValue(ht.at(-1));from.value=from.min;to.value=to.max;document.querySelector('#profileWeekdaySelect').innerHTML=pickerMarkup(['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag']);document.querySelector('#profileHourSelect').innerHTML=pickerMarkup(Array.from({length:24},(_,h)=>`${h}:00–${h+1}:00`));document.querySelector('#profileWindSelect').innerHTML=pickerMarkup(['Norden','Nordosten','Osten','Südosten','Süden','Südwesten','Westen','Nordwesten']);['profileWeekdaySelect','profileHourSelect','profileWindSelect'].forEach(bindProfilePicker);['profileFrom','profileTo'].forEach(id=>document.querySelector('#'+id).onchange=drawProfiles);document.querySelector('#profileReset').onclick=()=>{from.value=from.min;to.value=to.max;drawProfiles()}}
function selectedProfile(id){return[...document.querySelectorAll('#'+id+' input:checked')].map(x=>+x.value)}
function drawProfiles(){if(!hasSMPS())return;const H=D.heatmap,ht=H.time.map(x=>new Date(x)),from=document.querySelector('#profileFrom');if(!from.min)setupProfileControls();const start=new Date(from.value+'T00:00:00'),end=new Date(document.querySelector('#profileTo').value+'T23:59:59'),base=ht.map((d,i)=>d>=start&&d<=end?i:-1).filter(i=>i>=0),weekdays=selectedProfile('profileWeekdaySelect'),hours=selectedProfile('profileHourSelect'),sectors=selectedProfile('profileWindSelect'),wind=vals('WindDirection'),dayNames=['Montag','Dienstag','Mittwoch','Donnerstag','Freitag','Samstag','Sonntag'],sectorNames=['Norden','Nordosten','Osten','Südosten','Süden','Südwesten','Westen','Nordwesten'];
  document.querySelector('#profileCount').textContent=`${base.length.toLocaleString('de-DE')} SMPS-Scans im gewählten Zeitraum`;
  profileBars('profileOverall',[{idx:base,name:'Gesamtzeitraum'}]);
  profileBars('profileWeekday',weekdays.map(d=>({idx:base.filter(i=>(ht[i].getDay()+6)%7===d),name:dayNames[d]})));
  profileBars('profileHour',hours.map(h=>({idx:base.filter(i=>ht[i].getHours()===h),name:`${h}:00–${h+1}:00`})));
  profileBars('profileWind',sectors.map(sector=>({idx:base.filter(i=>{const j=Math.max(0,Math.min(times.length-1,Math.round((ht[i]-times[0])/300000))),wd=wind[j];return finite(wd)&&Math.floor(((wd+22.5)%360)/45)===sector}),name:sectorNames[sector]})))
}
function profileStats(idx){const y=[],ci=[];D.heatmap.z.forEach(row=>{const f=idx.map(i=>row[i]).filter(finite),m=mean(f);y.push(m);ci.push(f.length>1?1.96*sd(f)/Math.sqrt(f.length):null)});return{y,ci}}
function profileBars(id,groups){const H=D.heatmap,width=H.sizes.map((x,i)=>i===0?H.sizes[1]-x:i===H.sizes.length-1?x-H.sizes[i-1]:(H.sizes[i+1]-H.sizes[i-1])*.46),traces=groups.map((g,i)=>{const s=profileStats(g.idx),color=profileColors[i%profileColors.length];return{x:H.sizes,y:s.y,width,type:'bar',name:`${g.name} · n=${g.idx.length}`,marker:{color,opacity:.8,line:{color:'rgba(255,255,255,.45)',width:.4}},error_y:{type:'data',array:s.ci,visible:true,color,thickness:1,width:1.5},hovertemplate:'%{x:.1f} nm<br>Mittel %{y:.1f}<br>95-%-KI ±%{error_y.array:.1f}<extra>'+g.name+'</extra>'}});plot(id,traces,{barmode:'group',xaxis:{type:'log',title:'Partikelgröße (nm)'},yaxis:{title:'mittleres dN/dlogDp'},showlegend:groups.length>1,legend:{orientation:'h',y:1.15},annotations:groups.length?[]:[{text:'Bitte mindestens eine Gruppe auswählen',xref:'paper',yref:'paper',x:.5,y:.5,showarrow:false}]})}

function initMap(){const s=D.site,siteLabel=hasSMPS()?'CPC + SMPS':'4 Partikelzähler',coLocatedAir=distanceKm(s.latitude,s.longitude,s.airLatitude,s.airLongitude)<.03;document.querySelector('#mapSiteLegend').textContent=siteLabel;map=L.map('leafletMap',{zoomControl:true}).setView([s.latitude,s.longitude],siteId==='hoheduene'?13:12);setBasemap('street');L.circleMarker([s.latitude,s.longitude],{radius:9,color:'#fff',weight:3,fillColor:C.red,fillOpacity:1}).addTo(map).bindPopup(`<b>${siteLabel}</b><br>Partikelmesspunkt${coLocatedAir?'<br>'+s.airName:''}`);if(distanceKm(s.latitude,s.longitude,s.weatherLatitude,s.weatherLongitude)>=.03)L.circleMarker([s.weatherLatitude,s.weatherLongitude],{radius:8,color:'#fff',weight:3,fillColor:C.blue,fillOpacity:1}).addTo(map).bindPopup('<b>'+s.weatherName+'</b><br>Wetterdaten');[[s.airLatitude,s.airLongitude,s.airName],[s.air2Latitude,s.air2Longitude,s.air2Name]].filter(a=>a[2]&&finite(+a[0])&&finite(+a[1])&&distanceKm(s.latitude,s.longitude,a[0],a[1])>=.03).forEach(a=>L.circleMarker([a[0],a[1]],{radius:7,color:'#fff',weight:3,fillColor:C.green,fillOpacity:1}).addTo(map).bindPopup('<b>'+a[2]+'</b><br>Luftqualität'));
  document.querySelector('#basemap').onchange=e=>setBasemap(e.target.value);document.querySelector('#mapAverage').onchange=()=>{setSlider();updateMap()};['rainToggle','mapHeatmapToggle','plumeToggle','plumeLookback'].forEach(id=>document.querySelector('#'+id).onchange=updateMap);document.querySelector('#timeSlider').oninput=updateMap;document.querySelector('#play').onclick=togglePlay;setSlider();
}
let tileLayer;function setBasemap(type){if(tileLayer)tileLayer.remove();tileLayer=L.tileLayer(type==='satellite'?'https://server.arcgisonline.com/ArcGIS/rest/services/World_Imagery/MapServer/tile/{z}/{y}/{x}':'https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png',{maxZoom:19,attribution:type==='satellite'?'Tiles © Esri':'© OpenStreetMap'}).addTo(map)}
function setSlider(){const avg=+document.querySelector('#mapAverage').value,steps=Math.ceil(times.length/(avg/5)),sl=document.querySelector('#timeSlider');sl.max=Math.max(0,steps-1);sl.value=Math.min(+sl.value,+sl.max)}
function togglePlay(){playing=!playing;const b=document.querySelector('#play');b.textContent=playing?'■ Stopp':'▶ Start';clearInterval(playTimer);if(playing)playTimer=setInterval(()=>{const s=document.querySelector('#timeSlider');s.value=(+s.value+1)%(+s.max+1);updateMap()},380)}
function updateMap(){if(!D)return;const avg=+document.querySelector('#mapAverage').value,idx=Math.min(times.length-1,+document.querySelector('#timeSlider').value*(avg/5)),half=Math.max(1,Math.round(avg/10)),a=Math.max(0,idx-half),b=Math.min(times.length,idx+half+1),m=k=>mean(vals(k).slice(a,b));const wd=circularMean(vals('WindDirection').slice(a,b)),ws=m('WindSpeed'),rain=m('Precipitation'),s=D.site;
  const no2=series.AQ_NO2?'AQ_NO2':'ARPA_NO2',o3=series.AQ_O3?'AQ_O3':'ARPA_O3',pm10=series.AQ_PM10?'AQ_PM10':'ARPA_PM10',pm25=series.AQ_PM2_5?'AQ_PM2_5':'ARPA_PM2_5',shipCount=series.ShipPassages?sum(vals('ShipPassages').slice(a,b)):NaN,particleCards=particleKeys().map(k=>card(label(k).replace(/ \(.*\)$/,''),m(k),'#/cm³')).join(''),airCards=[no2,o3,pm10,pm25,'AQ_SO2'].filter(k=>series[k]).map(k=>card(label(k).replace(/ \(.*\)$/,''),m(k),'µg/m³')).join('');document.querySelector('#mapTime').textContent=fmt(times[idx]);document.querySelector('#mapValues').innerHTML=particleCards+(series.ShipPassages?card('Schiffspassagen',shipCount,`im ${avg}-min-Fenster`):'')+card('Wind',ws,'m/s · aus '+(finite(wd)?wd.toFixed(0):'–')+'°')+card('Regen',rain,'mm/h')+airCards;
  if(rainLayer)rainLayer.remove();if(document.querySelector('#rainToggle').checked&&finite(rain)&&rain>0)rainLayer=L.circle([s.weatherLatitude,s.weatherLongitude],{radius:300+rain*650,color:C.blue,fillColor:C.blue,fillOpacity:.18,weight:2}).addTo(map);
  if(shipLayer){shipLayer.remove();shipLayer=null}if(finite(shipCount)&&shipCount>0)shipLayer=L.circle([s.latitude,s.longitude],{radius:260+shipCount*90,color:C.orange,weight:3,fillColor:C.orange,fillOpacity:.2}).addTo(map).bindPopup(`<b>${shipCount} Schiffspassage${shipCount===1?'':'n'}</b><br>${fmt(times[idx])}`);
  drawPlume(idx,m(referenceKey()));drawPollutantPlumes(idx,a,b);windRose(vals('WindDirection').slice(a,b),wd);const colors=[C.red,C.blue,C.green,C.orange],R=resample('Precipitation',avg),airSelected=[...document.querySelectorAll('#mapPollutants input:checked')].map(x=>x.value),airColors=['#176b55','#e49242','#7d5ba6','#4f9298','#a26245','#b34ead','#687a2f'],traces=particleKeys().map((k,i)=>{const P=resample(k,avg);return{x:P.x,y:P.y,name:label(k).replace(/ \(.*\)$/,''),line:{color:colors[i%colors.length]}}});airSelected.forEach((k,i)=>{const A=resample(k,avg);traces.push({x:A.x,y:A.y,name:label(k),yaxis:'y2',line:{color:airColors[i%airColors.length],width:1.7}})});if(document.querySelector('#rainToggle').checked)traces.push({x:R.x,y:R.y,name:'Regen',yaxis:'y3',type:'bar',marker:{color:'rgba(50,119,184,.22)'}});if(series.ShipPassages){const S=resample('ShipPassages',avg);traces.push({x:S.x,y:S.y,name:'Schiffspassagen',yaxis:'y5',type:'bar',marker:{color:'rgba(228,146,66,.42)'}})}const showHeat=hasSMPS()&&document.querySelector('#mapHeatmapToggle').checked,H=D.heatmap;if(showHeat)traces.push({x:H.time,y:H.sizes,z:H.z.map(row=>row.map(v=>v>0?Math.log10(v):null)),type:'heatmap',xaxis:'x2',yaxis:'y4',colorscale:'Turbo',name:'SMPS-Verteilung',colorbar:{title:'log₁₀',len:.34,y:.17}});document.querySelector('#mapTrend').style.height=showHeat?'600px':'430px';const upper=showHeat?[.47,1]:[0,1],shapes=[{type:'line',xref:'x',yref:'paper',x0:times[idx],x1:times[idx],y0:upper[0],y1:upper[1],line:{color:'#b34ead',width:2}}];if(showHeat)shapes.push({type:'line',xref:'x2',yref:'paper',x0:times[idx],x1:times[idx],y0:0,y1:.34,line:{color:'#fff',width:2}});const mapLayout={hovermode:'x unified',xaxis:{domain:[0,.84],anchor:'y'},yaxis:{title:'Partikel #/cm³',domain:upper},yaxis2:{title:'Schadstoffe µg/m³',overlaying:'y',side:'right',showgrid:false},yaxis3:{title:'Regen mm/h',overlaying:'y',side:'right',anchor:'free',position:.94,showgrid:false},yaxis5:{title:'Schiffe',overlaying:'y',side:'right',anchor:'free',position:.88,showgrid:false},shapes,margin:{l:64,r:105,t:28,b:48}};if(showHeat){mapLayout.xaxis2={domain:[0,.84],anchor:'y4',title:'Datum'};mapLayout.yaxis4={domain:[0,.34],type:'log',title:'SMPS nm'}}plot('mapTrend',traces,mapLayout)
}
function quantile(a,q){const f=a.filter(finite).sort((x,y)=>x-y);if(!f.length)return NaN;const p=(f.length-1)*q,i=Math.floor(p);return f[i]+(f[Math.min(i+1,f.length-1)]-f[i])*(p-i)}
function destination(lat,lon,bearing,km){const R=6371,p=x=>x*Math.PI/180,d=km/R,b=p(bearing),la=p(lat),lo=p(lon),la2=Math.asin(Math.sin(la)*Math.cos(d)+Math.cos(la)*Math.sin(d)*Math.cos(b)),lo2=lo+Math.atan2(Math.sin(b)*Math.sin(d)*Math.cos(la),Math.cos(d)-Math.sin(la)*Math.sin(la2));return[la2*180/Math.PI,lo2*180/Math.PI]}
function drawPlume(idx,concentration){if(plumeLayer){plumeLayer.remove();plumeLayer=null}if(!document.querySelector('#plumeToggle').checked)return;const s=D.site,look=+document.querySelector('#plumeLookback').value,steps=Math.max(1,Math.round(look/5)),windSpeed=vals('WindSpeed'),windDirection=vals('WindDirection'),ref=referenceKey();if(!finite(D._cpcLo)){const cpc=vals(ref);D._cpcLo=quantile(cpc,.1);D._cpcHi=quantile(cpc,.9)}const lo=D._cpcLo,hi=D._cpcHi,level=finite(concentration)&&hi>lo?Math.max(0,Math.min(1,(concentration-lo)/(hi-lo))):.35,gray=Math.round(220-level*165),fill=`rgb(${gray},${gray},${gray})`,items=[],points=[[s.latitude,s.longitude]];let pos=points[0];for(let k=0;k<steps;k++){const j=Math.max(0,idx-k),ws=windSpeed[j],wd=windDirection[j];if(!finite(ws)||!finite(wd))continue;pos=destination(pos[0],pos[1],wd,Math.min(3,Math.max(0,ws)*.3));points.push(pos);const age=k/steps;items.push(L.circle(pos,{radius:210+age*690,color:fill,className:'particle-cloud',weight:.5,opacity:.3,fillColor:fill,fillOpacity:(.2+.52*level)*(1-age*.72),interactive:false}))}if(points.length>1)items.push(L.polyline(points,{color:'#273430',weight:1.6,opacity:.58,dashArray:'4 7',interactive:false}));plumeLayer=L.layerGroup(items).addTo(map)}
function pollutantColor(k){if(k.includes('NO2'))return'#7d5ba6';if(k.includes('PM10'))return'#e49242';if(k.includes('PM2_5'))return'#3277b8';if(k.includes('O3'))return'#1f8a70';if(k.endsWith('_NO'))return'#d75446';if(k.includes('BENZ'))return'#8a6048';return'#4f9298'}
function lighten(hex,level){const n=parseInt(hex.slice(1),16),mix=c=>Math.round(255+(c-255)*(.22+.78*level));return`rgb(${mix(n>>16)},${mix((n>>8)&255)},${mix(n&255)})`}
function pollutantStart(k){const s=D.site;return k.startsWith('AQ17SM_')?[s.air2Latitude,s.air2Longitude]:[s.airLatitude,s.airLongitude]}
function drawPollutantPlumes(idx,a,b){if(pollutantPlumeLayer){pollutantPlumeLayer.remove();pollutantPlumeLayer=null}const keys=[...document.querySelectorAll('#mapCloudPollutants input:checked')].map(x=>x.value),legend=document.querySelector('#pollutantCloudLegend');legend.innerHTML=keys.map(k=>`<em><i style="background:${pollutantColor(k)}"></i>${label(k).replace(/ \(.*\)$/,'')}</em>`).join('');if(!keys.length)return;D._pollutantScales=D._pollutantScales||{};const look=+document.querySelector('#plumeLookback').value,steps=Math.max(1,Math.round(look/5)),windSpeed=vals('WindSpeed'),windDirection=vals('WindDirection'),items=[];keys.forEach(k=>{const data=vals(k),value=mean(data.slice(a,b));if(!finite(value))return;if(!D._pollutantScales[k])D._pollutantScales[k]=[quantile(data,.1),quantile(data,.9)];const [lo,hi]=D._pollutantScales[k],level=hi>lo?Math.max(0,Math.min(1,(value-lo)/(hi-lo))):.3,color=pollutantColor(k),fill=lighten(color,level),points=[pollutantStart(k)];let pos=points[0];for(let q=0;q<steps;q++){const j=Math.max(0,idx-q),ws=windSpeed[j],wd=windDirection[j];if(!finite(ws)||!finite(wd))continue;pos=destination(pos[0],pos[1],wd,Math.min(3,Math.max(0,ws)*.3));points.push(pos);const age=q/steps;items.push(L.circle(pos,{radius:170+age*560,color:fill,className:'pollutant-cloud',weight:.4,opacity:.3,fillColor:fill,fillOpacity:(.16+.4*level)*(1-age*.75),interactive:false}))}if(points.length>1)items.push(L.polyline(points,{color,weight:1.2,opacity:.52,dashArray:'3 8',interactive:false}))});pollutantPlumeLayer=L.layerGroup(items).addTo(map)}
function card(n,v,u){return`<div>${n}<b>${finite(v)?v.toFixed(v>100?0:1):'–'}</b>${u}</div>`}
function circularMean(a){const f=a.filter(finite);if(!f.length)return NaN;const s=mean(f.map(x=>Math.sin(x*Math.PI/180))),c=mean(f.map(x=>Math.cos(x*Math.PI/180)));return(Math.atan2(s,c)*180/Math.PI+360)%360}
function windRose(a,wd){const bins=Array(16).fill(0);a.filter(finite).forEach(v=>bins[Math.floor(((v+11.25)%360)/22.5)]++);const theta=bins.map((_,i)=>i*22.5);const traces=[{type:'barpolar',r:bins,theta,width:Array(16).fill(20),marker:{color:C.blue,opacity:.72},name:'Häufigkeit'}];if(finite(wd))traces.push({type:'scatterpolar',r:[0,Math.max(1,...bins)],theta:[wd,wd],mode:'lines',line:{color:'#b34ead',width:4},name:'Mittel'});Plotly.react('windrose',traces,{margin:{l:22,r:22,t:28,b:20},paper_bgcolor:'rgba(0,0,0,0)',showlegend:false,polar:{angularaxis:{direction:'clockwise',rotation:90,tickfont:{size:9}},radialaxis:{showticklabels:false,gridcolor:C.grid}}},plotConfig)}
